### PR TITLE
ci: include dmg in release assets also

### PR DESCRIPTION
**Pull request by srevinsaju**

### CODE REVIEW

**Comment by srevinsaju** [comment]
@amanharwara should be fixed now

**Comment by amanharwara** [comment]
https://github.com/amanharwara/altus/runs/2146482346?check_suite_focus=true

Errors out at Release again.

**Comment by srevinsaju** [comment]
yes, because it was manually triggered. Would it be possible to do a post release? `4.1.1..post1` or `4.1.2`?

**Comment by amanharwara** [comment]
OK, I'll push a `4.1.0-continuous` tag.

**Comment by srevinsaju** [comment]
hmm.. something failed internally, within `marvinpinto/automatic-release-action`, let me see if I can debug

**Pull request merged**
