### PR TITLE
feat: remove unused addChatID and fix preload startup detection 

### PR DESCRIPTION
**Pull request by fznhq**
webview needs contextIsolation=false to make sure preload can access reactFiber object

### CODE REVIEW

**Review by amanharwara — CHANGES_REQUESTED** [review]
Hi, thanks for the contribution! I'm not sure what the chat IDs are actually being used for now. I believe I had implemented that for the chat online/offline indicator, but I've since stopped supporting that because it's difficult to keep up with changes in how WhatsApp handles that. I'm inclined to remove that file as well.

Please remove changes reload to that and delete that file as well. We can keep the changes to the preload that are not related to this.

Thanks again for your contribution.

**Comment by fznhq** [comment]
> Hi, thanks for the contribution! I'm not sure what the chat IDs are actually being used for now. I believe I had implemented that for the chat online/offline indicator, but I've since stopped supporting that because it's difficult to keep up with changes in how WhatsApp handles that. I'm inclined to remove that file as well.
> 
> Please remove changes reload to that and delete that file as well. We can keep the changes to the preload that are not related to this.
> 
> Thanks again for your contribution.

Sure

**Comment by fznhq** [comment]
@amanharwara thanks, but I forgot to remove the unused import addChatID on preload, can you do that?

**Comment by amanharwara** [comment]
> @amanharwara thanks, but I forgot to remove the unused import addChatID on preload, can you do that?

Yes, done.

**Comment by fznhq** [comment]
@amanharwara Thanks

**Pull request merged**
